### PR TITLE
Add support for `brotli` compression format

### PR DESCRIPTION
**Pull request by TharmiganK**
## Purpose

> $Subject

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6547

## Examples

See the issue for more details

## Checklist
- [x] Linked to an issue
- [x] Updated the changelog
- [x] Added tests
- [ ] ~Updated the spec~
- [x] Checked native-image compatibility
- [ ] ~Checked the impact on OpenAPI generation~

### CODE REVIEW

**Comment by TharmiganK** [comment]
This PR is on hold, since this new feature should be added to Update 11

**Comment by NipunaRanasinghe** [comment]
> This PR is on hold, since this new feature should be added to Update 11

@TharmiganK if this is deprioratized, better to close it ftm and we can reopen once we resume the work IMO

**Comment by TharmiganK** [comment]
> @TharmiganK if this is deprioratized, better to close it ftm and we can reopen once we resume the work IMO

No, we will merge this for Update 11. I will make this draft since I need to do some testing.

**Comment by TharmiganK** [comment]
Closing this for now and will reopen after the testing

**Pull request closed without merging**
